### PR TITLE
Make all links abs

### PR DESCRIPTION
**Pull request by avive**
Changed all links to abs to make the sidebar worked. So the pattern for links in mining folder is `mining/foo.md` - not great but should work ok for now.

### CODE REVIEW

**Comment by lrettig** [comment]
So the downside to doing this is that the links no longer work inline here in GitHub, which is kind of a shame. It might be worth trying to come up with something that works in both places. Let me think about it a little.

**Comment by avive** [comment]
Isn't that okay? the github files are the source and the rendering is on the protocol site. Not super comfortable while you view a file in github but the site is where we want devs to browse these - no?

**Comment by lrettig** [comment]
My working assumption has been that people are as likely to view these on GitHub as they are on the protocol site...

**Comment by lrettig** [comment]
Our options are:

- deal with broken links on at least one platform
- ditch the sidebar entirely
- find a better tool for rendering these
- hack the existing tool?

**Comment by avive** [comment]
fixed and can be closed as site moved fro docsify to docusuarus framework.

**Pull request closed without merging**
